name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Set Git user name
        run: git config --global user.name "Github Actions Bot"
      - name: Set Git user email
        run: git config --global user.email "githubactions@example.com"
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Generate index.html from portable.php
        run: php portable.php > index.html
      - name: Add index.html, style.css, and new markdown files to git
        run: git add index.html style.css && git ls-files -o --exclude-standard | xargs -n1 git add
      - name: Commit index.html, style.css, and new markdown files
        run: git commit -m "Generated index.html from portable.php, updated style.css, and added new markdown files"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
